---
title: "R Library CausalImpact on Inferring Causal Relationships"
output: html_notebook
---

 

```{r}
install.packages("CausalImpact")
library(CausalImpact)
```


**1. Linear Simulated Data**

```{r}
set.seed(1)
x1 <- 100 + arima.sim(model = list(ar = 0.999), n = 1000)
x2 <- 50 + arima.sim(model = list(ar = 0.8), n=1000) 
x3 <- 20 + arima.sim(model = list(ma=0.7), n =1000)
y <- 0.01*x1 + 0.3*x2 + 0.01 * x3 +rnorm(1000)
x1_range <- x1[701:1000]
y[701:1000] <- y[701:1000] + 0.05*x1_range + 5
```
```{r}
data <- cbind(y, x1, x2, x3)
```

```{r}
plot.ts(data)


```
```{r}
pre.period <- c(1, 700)
post.period <- c(701, 1000)
```

```{r}
impact <- CausalImpact(data, pre.period, post.period)

```

```{r}
plot(impact)
```

```{r}
summary(impact)

```


```{r}
summary(impact, "report")

```

**2. Nonlinear Simulated Data**
```{r}
x1 <- 100 + arima.sim(model = list(ar = 0.999), n = 1000)
x2 <- 50 + arima.sim(model = list(ar = 0.8), n=1000) 
x3 <- 20 + arima.sim(model = list(ma=0.7), n =1000)
y <- 0.1*(x1^2) + 0.03*(x2^3) + 0.01 * x3 +rnorm(1000)
x1_range <- x1[701:1000]
y[701:1000] <- y[701:1000] + 0.03*(x1_range^2) + 5
```
```{r}
nonlineardata <- cbind(y, x1, x2, x3)
```
```{r}
plot.ts(nonlineardata)

```
```{r}
pre.period <- c(1, 700)
post.period <- c(701, 1000)
```


```{r}
impact <- CausalImpact(nonlineardata, pre.period, post.period)

```
```{r}
plot(impact)
```
```{r}
summary(impact)
```

```{r}
summary(impact, "report")
```


**3. Observational Dataset: Policy Intervention by Central Bank **
# reference: https://nzlul.medium.com/causalimpact-analysis-using-r-4d9d4fdeb2d7
```{r}
setwd("/Users/ece/Downloads")
df <- read.csv("CausalExercise.csv")
```




```{r}
install.packages("psych")
library(psych)
describe(df)
```


```{r}
# Reference: https://nzlul.medium.com/causalimpact-analysis-using-r-4d9d4fdeb2d7

time.points <- seq.Date(as.Date("2020-02-27"), by = 1, length.out = 44)
ibcl <- ts(df$IBCL)
u10yr <- ts(df$VIX)
vix <- ts(df$VIX)
#Bind the data
data <- zoo(cbind(ibcl,u10yr,vix), time.points)
head(data)
```


```{r}
pre.period <- as.Date(c("2020-02-27","2020-03-23"))
post.period <- as.Date(c("2020-03-24","2020-04-10"))
```

```{r}
# default CausalImpact object initiated
impact <- CausalImpact(data, pre.period, post.period)
plot(impact)
```

```{r}
summary(impact)

```
```{r}
summary(impact, "report")

```

```{r}
# Adjusted model

adjusted_impact <- CausalImpact(data,pre.period, post.period, model.args = list(niter = 5000, nseasons = 7, season.duration = 1, dynamic.regression=TRUE, prior.level.sd=0.1))
plot(adjusted_impact)
```

```{r}
summary(impact)

```


```{r}
summary(impact, "report")
```









